import { existsSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const TEMPLATE = `# ClawGuard Configuration
# Generated by: clawguard init

# ── Proxy ────────────────────────────────────────────────
PORT=4100

# ── Budget Caps (USD) ────────────────────────────────────
# Set to a positive number to enable. Leave blank to disable.
CLAWGUARD_BUDGET_HOURLY=
CLAWGUARD_BUDGET_DAILY=10
CLAWGUARD_BUDGET_MONTHLY=100

# Warn when spend reaches this fraction of the cap (0–1)
CLAWGUARD_WARN_THRESHOLD=0.8

# ── Telegram Alerts ──────────────────────────────────────
# Get bot token from @BotFather, chat_id from @userinfobot
CLAWGUARD_TELEGRAM_BOT_TOKEN=
CLAWGUARD_TELEGRAM_CHAT_ID=

# ── Storage ──────────────────────────────────────────────
CLAWGUARD_DB_PATH=data/clawguard.db

# ── Logging ──────────────────────────────────────────────
# trace | debug | info | warn | error
LOG_LEVEL=info
`;

export async function init(args: string[]): Promise<void> {
  const outPath = resolve(process.cwd(), ".env");

  if (existsSync(outPath) && !args.includes("--force")) {
    console.error(`.env already exists. Use --force to overwrite.`);
    process.exit(1);
  }

  writeFileSync(outPath, TEMPLATE, "utf-8");
  console.log(`Created .env at ${outPath}`);
  console.log(`Edit it to set your budget caps and Telegram credentials, then run: clawguard start`);
}
